import Head from "next/head";
import { METADATA } from "../constants";
import Layout from "@/components/shared/layout";
import Header from "@/components/shared/header";
import React, { useEffect, useState } from "react";
import HeroSection from "@/components/hero";

export default function Home() {
  const renderBackdrop = (): React.ReactNode => <div className=' -z-1'></div>;
  return (
    <>
      <Head>
        <title>{METADATA.title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Header />
        <main className='flex-col flex'>
          {renderBackdrop()}
          <HeroSection />

          {/* <Footer /> */}
        </main>
      </Layout>
    </>
  );
}
