import Head from "next/head";
import { METADATA } from "../constants";

export default function Home() {
  return (
    <>
      <Head>
        <title>{METADATA.title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>Layout here</main>
    </>
  );
}
